all:
	gcc receiver_sigalrm.c -o receiver_sigalrm
	gcc receiver_select.c -o receiver_select
	gcc receiver_sockopt.c -o receiver_sockopt
	gcc sender_sigalrm.c -o sender_sigalrm
	gcc sender_select.c -o sender_select
	gcc sender_sockopt.c -o sender_sockopt

clean:
	rm receiver_sigalrm
	rm receiver_select
	rm receiver_sockopt
	rm sender_sigalrm
	rm sender_select
	rm sender_sockopt
	rm test*